image: maven:3.6.0-jdk-11

variables:
  DOCKER_HOST: "tcp://docker:2375" 
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  PROJECT_VERSION: 1.0.2
  JAR_FILE: basyx.components.AASServer-${PROJECT_VERSION}.jar
  AAS_SERVER_PROJECT_PATH: basyx.components/basyx.components.docker/basyx.components.AASServer
  ARTIFACT: ${AAS_SERVER_PROJECT_PATH}/target/$JAR_FILE
  MAVEN_CLI_OPTS: "-s ${CI_PROJECT_DIR}/.m2/settings.xml --batch-mode -Pgitlab"

cache:
  paths:
    - .m2/repository/
    
stages:
  - validate
  - build
  - publish

maven-validate:
  stage: validate
  tags:
    - basys
    - maven
  script:
    - cd basyx.components
    - mvn -V $MAVEN_CLI_OPTS validate
    
maven:
  stage: build
  tags:
    - basys
    - maven
  script:
    - cd basyx.components
    - mvn $MAVEN_CLI_OPTS install -Dmaven.validate.skip=true -Dmaven.test.skip=true
  artifacts:
    paths:
      - $ARTIFACT
    expire_in: 3 hour    
    
docker:
  stage: publish
  image: docker:20.10.12
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE_VERSION: 'dotaas-latest'
    DOCKER_IMAGE_TAG: 'aas-server'
    DOCKER_IMAGE: '$DOCKER_REGISTRY_USER/$DOCKER_IMAGE_TAG:$DOCKER_IMAGE_VERSION'
  services:
     - name: docker:20.10.12-dind
       # explicitly disable tls to avoid docker startup interruption
       command: ["--tls=false"]
  dependencies:
    - maven
  tags:
    - basys
    - docker
  before_script:
    - docker info      
  script:
    - cd $AAS_SERVER_PROJECT_PATH
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - docker build -t "$DOCKER_IMAGE" \
        --build-arg JAR_FILE=$JAR_FILE \
        --build-arg PORT=8080 \
        --build-arg AAS_CONFIG_KEY=aas-config \
        --build-arg CONTEXT_CONFIG_KEY=context-config \
        --build-arg MONGODB_CONFIG_KEY=mongodb-config \
        .  ARG PORT
    - docker push "$DOCKER_IMAGE"
  rules:
    - if: $CI_COMMIT_BRANCH == 'feature/dotaas-registry'
